#!/bin/bash

BSBM="$HOME/Projects/BSBM"
source "$BSBM/bin/bsbm_init"

#cecho "$CP"
## --------

DATADIR="Data"
if [ ! -e "$DATADIR" ]
then
    echo "**** Data directory does not exist: $DATADIR"
    exit 1 
fi

## --------
## JVM_ARGS="-Xmx2000M -server"

PROGRAM=benchmark.testdriver.TestDriver

DATADIR=Data
ARGS="$@"

function ping {
    curl --silent --fail --head "http://localhost:3030/ds"
    if [ $? != 0 ]
    then
	echo "No server?" 2>&1
	exit 1
    fi
}

function runOne {
    local SIZE="$1"
    if [ "$SIZE" = "" ]
    then
	echo "No size" 2>&1
	return
    fi

    
    SET="$DATADIR/data-$SIZE"
    STORE="$SET/Store"
    DB="$STORE/DB-$SIZE"

    if [ ! -e "$DB" ]
    then
	echo "No database for $DB/Store"
	return
    fi
    echo "==== Performance run for $SIZE"
    echo "== Start: $(date +"%Y-%m-%d %H:%M:%S")"
    java -cp "$CP" $JVM_ARGS \
	 -Dlog4j.configuration=file:log4j.properties \
	 $PROGRAM \
	 $ARGS -idir "$SET" -o "Results/res-$SIZE.xml" \
         "jena:$STORE/assembler.ttl"
	 #"http://localhost:3030/ds/sparql"
    echo "== Finish: $(date +"%Y-%m-%d %H:%M:%S")"
}

mkdir -p Results

#ping
runOne 1m
